// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABxeKsUz_wgb0cOeXvxh9D2r1V5GlFt8Q',
    appId: '1:263458504040:web:38b20fa7a17a3706092add',
    messagingSenderId: '263458504040',
    projectId: 'crafty-bay-d2c8c',
    authDomain: 'crafty-bay-d2c8c.firebaseapp.com',
    storageBucket: 'crafty-bay-d2c8c.firebasestorage.app',
    measurementId: 'G-YNFE8GP5BY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf6nv1Nv4Rc-jvHt22P0ZZl3E1hxcVBbk',
    appId: '1:263458504040:android:f3f66126226b8350092add',
    messagingSenderId: '263458504040',
    projectId: 'crafty-bay-d2c8c',
    storageBucket: 'crafty-bay-d2c8c.firebasestorage.app',
  );
}
